defaults:
  - _self_
  - model: resnet18

device: cuda
dataset: cifar10
num_seeds: 3
random_seed: 42

al:
  n_cycles: 9
  initial_pool_size: 250
  query_size: 250
  query_strategy: random
  log_interval: 20

ssl:
  use: False
  rampup_length: 50
  lambda_u: 50
  alpha: 0.5
  T: 0.75
  n_train_iterations: 100

pretrain:
  use: False
  projection_dim: 128

path:
  output_dir: ./output
  data_dir: ./data
  initial_pool_dir: ./storage/initial_pools
  final_pool_dir: ./storage/final_pools
  model_dir: ./storage/pretrained_models


hydra:
  run:
    dir: ${path.output_dir}